Add some checks for microk8s addons

diff --git a/qa-deploy b/qa-deploy
--- a/qa-deploy
+++ b/qa-deploy
@@ -69,7 +69,10 @@ function run_microk8s() {
 	exit 1
     fi
 
-    microk8s.enable ingress
+    if ! microk8s.kubectl get service/default-http-backend &> /dev/null; then
+        echo "HTTP backend not found: Enabling ingress addon"
+        microk8s.enable ingress
+    fi
 }
 
 function deploy_service() {
